# Environment Configuration Examples for Serverless Application
# This file provides different environment configurations for the serverless application

# Development Environment Configuration
development:
  # Lambda Configuration
  lambda:
    memory_size: 128
    timeout: 30
    runtime: python3.9
    environment_variables:
      LOG_LEVEL: DEBUG
      ENVIRONMENT: dev
      DB_CONNECTION_POOL_SIZE: 5
      
  # API Gateway Configuration
  api_gateway:
    stage: dev
    throttling:
      rate_limit: 100
      burst_limit: 200
    caching:
      enabled: false
      ttl_in_seconds: 0
      
  # DynamoDB Configuration
  dynamodb:
    billing_mode: PAY_PER_REQUEST
    point_in_time_recovery: false
    deletion_protection: false
    
  # S3 Configuration
  s3:
    versioning: false
    encryption: AES256
    lifecycle_days: 30
    
  # Monitoring
  monitoring:
    x_ray_tracing: false
    detailed_monitoring: false
    log_retention_days: 7

---

# Staging Environment Configuration
staging:
  # Lambda Configuration
  lambda:
    memory_size: 256
    timeout: 60
    runtime: python3.9
    environment_variables:
      LOG_LEVEL: INFO
      ENVIRONMENT: staging
      DB_CONNECTION_POOL_SIZE: 10
      
  # API Gateway Configuration
  api_gateway:
    stage: staging
    throttling:
      rate_limit: 500
      burst_limit: 1000
    caching:
      enabled: true
      ttl_in_seconds: 300
      
  # DynamoDB Configuration
  dynamodb:
    billing_mode: PAY_PER_REQUEST
    point_in_time_recovery: true
    deletion_protection: true
    
  # S3 Configuration
  s3:
    versioning: true
    encryption: KMS
    lifecycle_days: 90
    
  # Monitoring
  monitoring:
    x_ray_tracing: true
    detailed_monitoring: true
    log_retention_days: 30

---

# Production Environment Configuration
production:
  # Lambda Configuration
  lambda:
    memory_size: 512
    timeout: 300
    runtime: python3.9
    environment_variables:
      LOG_LEVEL: WARN
      ENVIRONMENT: production
      DB_CONNECTION_POOL_SIZE: 20
      
  # API Gateway Configuration
  api_gateway:
    stage: prod
    throttling:
      rate_limit: 2000
      burst_limit: 5000
    caching:
      enabled: true
      ttl_in_seconds: 600
      
  # DynamoDB Configuration
  dynamodb:
    billing_mode: PROVISIONED
    read_capacity: 100
    write_capacity: 100
    point_in_time_recovery: true
    deletion_protection: true
    
  # S3 Configuration
  s3:
    versioning: true
    encryption: KMS
    lifecycle_days: 365
    mfa_delete: true
    
  # Monitoring
  monitoring:
    x_ray_tracing: true
    detailed_monitoring: true
    log_retention_days: 365
    
  # Auto Scaling
  auto_scaling:
    dynamodb:
      target_utilization: 70
      scale_in_cooldown: 60
      scale_out_cooldown: 60
      
  # Backup
  backup:
    dynamodb_backup: true
    s3_cross_region_replication: true